import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';
import localFont from 'next/font/local';
import "./global.css";
import Cabecalho from "@/components/Cabecalho";
import StyledComponentsRegistry from '@/../lib/registry';


// Fontes locais
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Fonte Montserrat do Google Fonts
const montserrat = Montserrat({
  weight: ['400', '500', '700'], // Pode ajustar os pesos que deseja usar
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "GAID",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" href="/assets/favicon.ico" type="image/x-icon" />
        <title>GAID</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.className}`}>
        <StyledComponentsRegistry>
          <Cabecalho/>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
